In [6]:
import numpy as np


a = np.arange(20).reshape(4,5)
print(a)
print(np.zeros((2,3)))
print(a[0],a[:,2],a[1:,::2])
print(a[a > 10])
print((a+10).shape,(a*2)[0,0])
x = np.arange(4).reshape(4,1); y = np.arange(3).reshape(1,3)
print((x+y).shape)
b = np.random.randn(4,5)
print((a*b)[0,0],(a @ b.T)[0,0])
print(a.sum(),a.sum(axis=0))
print(a.mean(),a.mean(axis=1))
print(a.T.shape,a.reshape(2, 10).shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3 4] [ 2  7 12 17] [[ 5  7  9]
 [10 12 14]
 [15 17 19]]
[11 12 13 14 15 16 17 18 19]
(4, 5) 0
(4, 3)
-0.0 2.534921883780857
190 [30 34 38 42 46]
9.5 [ 2.  7. 12. 17.]
(5, 4) (2, 10)


In [7]:
import torch
t = torch.from_numpy(a)
print(t.dtype)
print(t.float().numpy())

torch.int64
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
